package com.rinsing.geomantia.systems.realm_planning.application.access;

import java.util.*;
import java.util.function.BiFunction;

/** Bounded, deterministic terrain-only search. No chunks are generated by this policy. */
public final class StarterLandSelector {
    public record Ground(int feetY, boolean dry) { }
    public record Site(int x, int y, int z) { }
    public static Site select(int preferredX, int preferredZ, int surveyRadius, int initialRadius,
                              BiFunction<Integer,Integer,Ground> sampler) {
        int limit = surveyRadius - initialRadius - InitialExplorationArea.GENERATION_HALO_BLOCKS;
        if (limit < 0) throw new IllegalArgumentException("STARTER_SURVEY_TOO_SMALL");
        Map<Long,Ground> cache = new HashMap<>();
        BiFunction<Integer,Integer,Ground> ground = (x,z) -> cache.computeIfAbsent(
                ((long)x << 32) ^ (z & 0xffffffffL), ignored -> sampler.apply(x,z));
        int spacing = Math.max(64, Math.min(1024, initialRadius / 2));
        Site preferred = check(preferredX, preferredZ, limit, spacing, ground);
        if (preferred != null) return preferred;
        // 512-block lattice, nearest rings first; at most 4096 candidate centres.
        int attempted = 0;
        for (int ring=0; ring <= limit/512; ring++) {
            for (int z=-ring; z<=ring; z++) for (int x=-ring; x<=ring; x++) {
                if (Math.max(Math.abs(x),Math.abs(z)) != ring) continue;
                if (++attempted > 4096) throw new IllegalStateException("STARTER_LAND_SEARCH_BUDGET_EXHAUSTED");
                Site site = check(x*512,z*512,limit,spacing,ground);
                if (site != null) return site;
            }
        }
        throw new IllegalStateException("STARTER_SUITABLE_LAND_NOT_FOUND: enlarge W or choose another terrain seed");
    }
    private static Site check(int x,int z,int limit,int spacing,BiFunction<Integer,Integer,Ground> sample) {
        if (Math.abs((long)x)>limit || Math.abs((long)z)>limit) return null;
        Ground centre=sample.apply(x,z);
        if (!centre.dry()) return null;
        int land=0;
        for(int dz=-1;dz<=1;dz++) for(int dx=-1;dx<=1;dx++) {
            Ground g=sample.apply(x+dx*spacing,z+dz*spacing);
            if(g.dry()) land++;
        }
        if(land<7) return null; // Reject tiny islands and coast-only spawn points.
        for(int[] d:new int[][]{{8,0},{-8,0},{0,8},{0,-8}}) {
            Ground g=sample.apply(x+d[0],z+d[1]);
            if(!g.dry() || Math.abs(g.feetY()-centre.feetY())>4) return null;
        }
        return new Site(x,centre.feetY(),z);
    }
}
