import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const base = process.env.STUDIO_URL ?? 'http://127.0.0.1:8765';
const browser = await chromium.launch({headless: true, executablePath: process.env.STUDIO_CHROMIUM, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader']});
fs.mkdirSync('runtime', {recursive: true});
try {
  const page = await browser.newPage({viewport: {width: 1440, height: 1000}});
  page.setDefaultTimeout(15000);
  const errors = []; page.on('pageerror', err => errors.push(String(err)));
  await page.goto(`${base}/?asset=SR-F01-v01`);
  await page.waitForFunction(() => window.studio?.telemetry.ready, null, {timeout: 60000});
  const total = (await (await fetch(`${base}/api/catalog`)).json()).length;
  const resultCount = () => page.locator('#assets button').count();
  assert.equal(await resultCount(), total);
  const roleSelect = page.getByRole('combobox', {name: '规划角色', exact: true});
  await roleSelect.selectOption('core');
  assert.equal(await resultCount(), 49);
  assert.deepEqual([...new Set(await page.locator('#assets .role-badge').allTextContents())], ['核心']);
  await page.reload();
  await page.waitForFunction(() => window.studio?.telemetry.ready);
  assert.equal(await roleSelect.inputValue(), 'core');
  assert.equal(await resultCount(), 49);
  await page.getByRole('combobox', {name: '建筑风格', exact: true}).selectOption('蒸汽朋克');
  assert.equal(await resultCount(), 1);
  assert.match(await page.locator('#assets').innerText(), /SR-01-v01/);
  await roleSelect.selectOption('fill');
  assert.equal(await resultCount(), 14);
  await page.getByRole('button', {name: '清空筛选', exact: true}).click();
  assert.equal(await roleSelect.inputValue(), '');
  assert.equal(await resultCount(), total);
  async function addUse(path) {
    for (const [level, id] of path.entries()) await page.locator(`#function-level-${level}`).selectOption(id);
    await page.getByRole('button', {name: '按此用途筛选', exact: true}).click();
  }
  await addUse(['commerce', 'retail', 'retail.food', 'retail.food.bread']);
  assert.equal(await resultCount(), 6);
  await roleSelect.selectOption('core');
  assert.equal(await resultCount(), 0);
  await roleSelect.selectOption('fill');
  assert.equal(await resultCount(), 6);
  await roleSelect.selectOption('');
  await addUse(['production', 'production.food', 'production.food.baking']);
  assert.equal(await resultCount(), 6);
  await addUse(['housing', 'housing.family']);
  assert.equal(await resultCount(), 1);
  assert.match(await page.locator('#assets').innerText(), /SR-F01-v01/);
  await page.getByRole('combobox', {name: '用途匹配方式', exact: true}).selectOption('any');
  assert.ok(await resultCount() > 6);
  await page.getByRole('combobox', {name: '建筑风格', exact: true}).selectOption('北欧');
  assert.ok(await resultCount() > 0);
  await page.getByRole('combobox', {name: '用途匹配方式', exact: true}).selectOption('all');
  assert.equal(await resultCount(), 0);
  assert.ok(await page.locator('#selection-note').isVisible());
  await page.getByRole('button', {name: '清空筛选', exact: true}).click();
  assert.equal(await resultCount(), total);
  assert.ok(await page.locator('#selection-note').isHidden());
  await page.locator('.extra-filters summary').click();
  await page.getByRole('combobox', {name: '原始功能标签', exact: true}).selectOption('工具维修');
  assert.equal(await resultCount(), 7);
  await page.getByRole('combobox', {name: '原始功能标签', exact: true}).selectOption('');
  await page.getByRole('searchbox', {name: '选址说明关键词', exact: true}).fill('车站周边或其他有人流的聚落街区');
  assert.equal(await resultCount(), 0); // This text is a recommendation, not a site condition.
  await page.getByRole('button', {name: '清空筛选', exact: true}).click();
  await page.getByRole('searchbox', {name: '查找结构', exact: true}).fill('烘焙 商业');
  assert.equal(await resultCount(), 6);
  await page.getByRole('searchbox', {name: '查找结构', exact: true}).fill('');
  await addUse(['commerce', 'retail', 'retail.food']);
  assert.ok(await resultCount() >= 6);
  await page.locator('#selected-functions button').click();
  assert.equal(await resultCount(), total);
  // Detail tags are actual controls, and survive model navigation/reload.
  await page.locator('#function-tags button').filter({hasText: '烘焙'}).click();
  await page.locator('#original-tags button').filter({hasText: /^零售$/}).click();
  assert.equal(await resultCount(), 6);
  await page.locator('#assets button').filter({hasText: 'AA-F01-v01'}).click();
  await page.waitForFunction(() => window.studio?.telemetry.ready && window.studio.telemetry.id === 'AA-F01-v01');
  assert.equal(new URL(page.url()).searchParams.get('functions'), 'production.food.baking');
  assert.equal(new URL(page.url()).searchParams.get('tag'), '零售');
  await page.reload();
  await page.waitForFunction(() => window.studio?.telemetry.ready);
  assert.equal(await resultCount(), 6);
  assert.equal(await page.locator('#selected-functions button').count(), 1);
  assert.equal(await page.locator('#raw-tag').inputValue(), '零售');
  await page.screenshot({path: 'runtime/filter-review-desktop.png'});
  await page.locator('main').evaluate(el => { el.scrollTop = el.scrollHeight; });
  await page.screenshot({path: 'runtime/filter-review-details.png'});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.setViewportSize({width: 760, height: 900});
  await page.screenshot({path: 'runtime/filter-review-narrow.png'});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.deepEqual(errors, []);
  assert.deepEqual(await page.evaluate(() => window.studio.telemetry.renderErrors), []);
  assert.deepEqual(await page.evaluate(() => window.studio.telemetry.missingTextures), []);
  console.log('PASS: hierarchy, parent matching, AND/OR, style intersection, exact tags, site/recommendation separation, empty/reset, clickable detail tags, URL persistence, responsive layout, real NBT rendering');
} finally { await browser.close(); }
