import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const base=process.env.STUDIO_URL??'http://127.0.0.1:8765';
const browser=await chromium.launch({headless:true,executablePath:process.env.STUDIO_CHROMIUM,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{
  const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
  const errors=[];page.on('pageerror',e=>errors.push(String(e)));
  await page.goto(`${base}/?asset=SR-F01-v01`);
  await page.waitForFunction(()=>window.studio?.telemetry.ready);
  await page.getByRole('searchbox',{name:'查找结构',exact:true}).fill('不存在的结构');
  assert.equal(await page.locator('#assets button').count(),0);
  await page.getByRole('searchbox',{name:'查找结构',exact:true}).fill('面包');
  assert.ok(await page.locator('#assets button').count()>=1);
  assert.equal(await page.locator('#assets button').filter({hasText:'SR-F01-v01'}).count(),1);
  await page.getByRole('button',{name:'去屋顶',exact:true}).click();
  assert.equal(await page.locator('#roof').getAttribute('class'),'selected');
  await page.getByRole('combobox',{name:'楼层',exact:true}).selectOption('1');
  assert.equal(await page.locator('#clip-y').inputValue(),'11');
  await page.getByRole('button',{name:'标记',exact:true}).click();
  assert.ok(await page.locator('.pin').count()>0);
  await page.getByRole('button',{name:'还原',exact:true}).click();
  await page.getByRole('button',{name:'室内漫游',exact:true}).click();
  assert.match(await page.locator('#view-note').innerText(),/W A S D/);
  await page.keyboard.press('w');
  await page.getByRole('button',{name:'前侧',exact:true}).click();
  const download=page.waitForEvent('download');
  await page.getByRole('button',{name:'保存当前视图',exact:true}).click();
  assert.match((await download).suggestedFilename(),/^SR-F01-v01-front\.png$/);
  const result=await page.evaluate(()=>window.studio.telemetry);
  assert.deepEqual(result.renderErrors,[]);assert.deepEqual(result.missingTextures,[]);assert.deepEqual(errors,[]);
  assert.equal((await fetch(`${base}/api/model?id=../../.git/config`)).status,404);
  assert.equal((await fetch(`${base}/resources/%2e%2e%2f%2e%2e%2fpackage.json`)).status,404);
  await page.evaluate(()=>window.studio.load('WT-01-v01'));
  const before=await page.evaluate(()=>({model:JSON.stringify(window.studio.model),image:document.querySelector('canvas').toDataURL()}));
  await page.getByRole('button',{name:'地形示意',exact:true}).click();
  const after=await page.evaluate(()=>({model:JSON.stringify(window.studio.model),image:document.querySelector('canvas').toDataURL()}));
  assert.equal(before.model,after.model);assert.notEqual(before.image,after.image);
  assert.match(await page.locator('#axis').innerText(),/不写入 NBT/);
  await page.evaluate(()=>window.studio.load('WT-04-v01'));
  const canalBefore=await page.evaluate(()=>({model:JSON.stringify(window.studio.model),image:document.querySelector('canvas').toDataURL()}));
  await page.getByRole('button',{name:'地形示意',exact:true}).click();
  const canalAfter=await page.evaluate(()=>({model:JSON.stringify(window.studio.model),image:document.querySelector('canvas').toDataURL()}));
  assert.equal(canalBefore.model,canalAfter.model);assert.notEqual(canalBefore.image,canalAfter.image);
  await page.evaluate(()=>window.studio.load('SR-F01-v01'));
  assert.ok(await page.locator('#context').isDisabled());
  assert.match(await page.locator('#axis').innerText(),/X 东/);
  const end=await page.evaluate(()=>window.studio.telemetry);
  assert.deepEqual(end.renderErrors,[]);assert.deepEqual(end.missingTextures,[]);assert.deepEqual(errors,[]);
  console.log('PASS: search, floor/roof, markers, walk, PNG download, render telemetry, confined paths, non-mutating shore/canal context');
}finally{await browser.close();}
