package com.rinsing.geomantia.systems.city.application;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

/** Designer-facing explanation of capabilities actually present in this frozen catalog. */
final class CityDesignGuide {
    private CityDesignGuide() { }
    static JsonObject from(CityBlueprintReferenceCatalog catalog) {
        JsonObject guide = new JsonObject();
        guide.addProperty("semanticAuthority", "pack_author_annotations_only");
        guide.addProperty("designGoal", "Design comes first: act as a bold, terrain-aware city designer, not a submission validator. Compose a civilization whose structures have purposeful functions, coherent style, clear hierarchy and useful spatial relationships. Use available arrays, nesting and deliberate counts ambitiously where the terrain and chosen assets support the idea. A valid compilation is the start of visual judgement, not the design goal. Do not infer functions/styles from names or appearances.");
        guide.addProperty("workflow", "Review terrain; submit designIntent (groupId, role, intent, preferredPatchRefs) through city_submit_d4_blueprint. Batch materialSelections per intended group to search authored metadata or select structureRefs/fillPoolRefs and receive capacity estimates. Design complete nested clusters using DRAFT, inspect planned/retained counts and gaps, revise locally, then FINAL. A cluster can contain many children in one call. Approximately 20 calls / 5 minutes is an efficiency goal, not a rejection limit.");
        JsonObject loop = new JsonObject();
        loop.addProperty("districtInitial", "Inspect terrain BEFORE choosing a composition. Read this city's function, scaleDesignTask and authored material pool; select a suitable Top Patch and state the district's purpose and spatial idea. Design one functional district, including multiple child arrays where useful, in DRAFT. Retain previous districts. A functional district need not equal a single leaf group. New designIntent groups merge with existing intents.");
        loop.addProperty("scaleAndNesting", "Use scaleDesignTask's scale-specific requirements. Its suggested initial array range is a starting estimate, NOT a cap, target to tick off or reason to stop refining. Larger counts, additional purposeful arrays and richer nesting are welcome when the preview needs them. CITY and LARGE_CITY need a substantial composed main body, not just several unrelated arrays or token nesting. Choose structureCount deliberately using selected NBT sizes and capacity estimates. Compose children around an intended shared space, frontage, landmark or activity; do not mechanically repeat one recipe, always use COMPACT, or inflate nesting depth for its own sake. Small settlements may stay simple. No new hard area or retained-building threshold.");
        loop.addProperty("districtRefinement", "Request the district's local images through designReview (batch up to 3 child groupIds). Inspect retained size, terrain skips, spacing, orientation, hierarchy and whether the intended shared space is visible. Record an assessment, then change counts, array or parent parameters, template choices or explicit adjacent arrays where useful. Recompile DRAFT and review the affected result. After deleting buildings, reducing counts or removing a composition, compare the remaining result with the original intent. If the district loses its scale, frontage, shared space or supporting functions, repair it using suitable placement, parameters, materials or purposeful additions; do not merely lower the request to match survivors. Keep what works and explain why in visible spatial terms; do not reflexively switch algorithms after a parameter error. Finish this district's review before designing the next.");
        loop.addProperty("cityRefinement", "After districts have been reviewed, request designReview overview=true. Read the whole city's hierarchy, separations, routes and purposeful open spaces. Where a transition is missing, explicitly design an outward array with a stated function and appropriate templates, using existing ADJACENCY/DIRECTION and CONNECTION capabilities. Adjust existing compositions when that is better. Do not fill every gap or connect districts by random buildings. Judge separation from the actual overview: adjust overly distant groups or add designed transitions when needed. Empty space is acceptable when its location and purpose are visible; do not justify unexplained gaps with generic breathing-room claims. Preserve useful landscape. Review changed local results and the final overview before FINAL.");
        loop.addProperty("judgement", "The host tracks which current previews have a model assessment, not whether a city is beautiful. Assess the original intent against visible evidence: shared-space form, frontage continuity, relative distances, hierarchy and retained scale. Full retention, non-empty districts, enough array containers or completed reviews alone do not establish quality. Identify shortcomings and act on them before FINAL where the available tools can address them; distinguish host blockers from design choices. Preserving valid groups means avoiding unrelated damage during error recovery, not freezing a successful but weak layout. If keeping a design, explain concretely why its spatial relationships work. Unsupported decorations, walls, bridges or shopfront features must not be claimed as built. Work with available authored assets and tools. There is no compulsory number of cosmetic edits or extra rejection budget for these review stages.");
        guide.add("designLoop", loop);
        guide.addProperty("placementBoundary", "A chosen Patch locates the planned array within the preview boundary. Specify structureCount per leaf array; default uses extent and algorithm. The host freezes the array, then filters individual buildings for terrain/collisions without moving survivors or filling holes. Empty arrays remain visible in the review. No automatic buildings for area targets or connections. ADJACENCY places complete array envelopes nearby; CONNECTION only requests roads.");
        JsonArray algorithms = new JsonArray();
        catalog.algorithmsByProfileRef().entrySet().stream().sorted(java.util.Map.Entry.comparingByKey()).forEach(entry -> {
            JsonObject algorithm = new JsonObject();
            algorithm.addProperty("algorithmProfileRef", entry.getKey());
            algorithm.addProperty("algorithm", entry.getValue());
            algorithm.addProperty("designUse", switch (entry.getValue()) {
                case "GRID" -> "Ordered rows of buildings with internal street clearance; suitable when regular blocks serve the design.";
                case "LINEAR" -> "Arrange buildings along a shared direction; consider a narrow terrain corridor or frontage.";
                case "COURTYARD" -> "Arrange around shared inner space; reserve enough room for the court and surrounding buildings.";
                case "CENTER_SYMMETRIC" -> "Commit the center first, then symmetric fill pairs; both sides need usable space.";
                case "COMPACT", "ORGANIC_COMPACT" -> "Grow a compact group from its chosen origin while respecting local terrain and clearance.";
                default -> throw new IllegalArgumentException("Unsupported design algorithm: " + entry.getValue());
            });
            algorithms.add(algorithm);
        });
        guide.add("availableArrayCapabilities", algorithms);
        guide.addProperty("composition", "Read scaleDesignTask first. Use arrayCompositions to arrange whole child groups with any catalog array algorithm. A member group may itself be the centerGroupId of another composition; no duplicate parents or cycles. Leaf groups are counted once. Preserve authored functions and templates, do not replace the design with district presets. HIERARCHY expresses functional parent/child relationships only; it does not order geometric compilation or override composition centers. Functional hierarchy itself must be acyclic. BETWEEN_GROUPS references and array composition dependencies must separately be acyclic. Road ports are computed by the host.");
        guide.addProperty("boundaryPlacement", "Use existing placementRelation ALONG_PATCH_BOUNDARY with two adjacent patchRefs: first is the placement side, second is the opposite side. For COMPACT/ORGANIC_COMPACT buildings follow actual shared edges; a non-symmetric parent composition with this center relation arranges whole child arrays along those edges. CENTER_SYMMETRIC retains its symmetry rather than bending members along a curved bank. Missing shared edges are reported, never silently replaced by ordinary placement. Water and terrain checks remain unchanged. Do not infer a bridge or require both banks.");
        guide.addProperty("landscapes", "Design required landscape with its owner group before array fill. Use growth={seed:{x,z},targetCellCount,allowedLandformTypes} on required ATTACHED landscapes for independent size: choose a world-coordinate seed inside the design preview and copy landformType names from terrain data (empty list allows all otherwise admissible landforms). One cell is cellStepBlocks squared from the current terrain grid, not a chunk or a building; targetCellCount is the total per instance, distributed over parcelCount. This demand replaces building-area percentages. Cell shortage, clipped parcels and approximate content shares are preview feedback, not submission failures. Inspect actual area and shape, then adjust the seed/count/content if needed. The host preserves that initial shape and excludes later buildings and roads; a clipped field is reported, never allowed to overwrite a building or silently relocated.");
        guide.addProperty("roads", "Only explicit CONNECTION relations create main roads, and they must serve real destinations. Mere adjacency or a desire to fill a gap is not a road or bridge request.");
        guide.addProperty("recovery", "On a design rejection preserve unchanged groups. Prefer baseBlueprintHash + blueprintPatch (replace-only JSON Pointer) to change only the reported group or relation. Do not change generationSeed. The host reuses successful exact-input array checkpoints; changed terrain, placement inputs or occupied dependencies invalidate them. Shared roads and final safety are always rechecked. Missing author metadata or program geometry failures are host blockers, not a redesign request.");
        return guide;
    }
}
